# -*- coding: utf-8 -*-
"""face recognition .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b1Bp9N2ZArnDV4a9L9wl2wx2Aph3XmUq
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier

from google.colab import drive
drive.mount('/content/gdrive')

path = "/content/gdrive/MyDrive/Colab Notebooks/"
x_train = np.load("/content/gdrive/MyDrive/Colab Notebooks/x_train_new.npy")
y_train = np.load("/content/gdrive/MyDrive/Colab Notebooks/ Y_train.npy")

print(type(x_train), type(y_train))

print(x_train.shape, y_train.shape)

print(y_train[-5:])

plt.imshow(x_train[0].reshape(100,100,3))

knn = KNeighborsClassifier()
# train
knn.fit(x_train, y_train)

knn.predict(x_train[:5])

x_train[8].shape

y_train[:5]

print(y_train[8])
plt.imshow(x_train[8].reshape(100,100,-1))

(x_train[5].reshape(1,-1)).shape